### ISSUE TITLE
Assignment 4 Bokeh 

### ISSUE THREAD

**Issue by ThatkidfromA** [neuniversity/ALY6140#19]
Hi classmates,

I am encountering issues using bokeh to make scatterplots. The output result come back as full filled color. I have followed the instructions from "https://programminghistorian.org/en/lessons/visualizing-with-bokeh", but the result is wrong. 
This is my code: 
from bokeh.io import output_notebook
  y=tips['tip']
  x=tips['total_bill']
  z=tips

  p = figure(x_axis_label='x', y_axis_label='y')
  p.circle(x,y,size=1000, color = 'red', alpha=0.5)
  show(p)

**Comment by echolq012** [comment]
Hi there, 
I have tried your code in my Jupyter notebook, and please delete 'size=1000' in your code and then run again. The size or diameter values for the markers in screen space units. That's why you have full filled color in your graph.

Best,
Qing Li

**Comment by ThatkidfromA** [comment]
Hi Qing li,

Thank you for helping me. The problem has been solve. But, the answer pop into another windows. Does the professor want the output on another windows or the output has to be able to view without opening a new window?

**Comment by echolq012** [comment]
I thought that is the core difference between Bokeh and other libraries. You can use web browser for interactive visualization. The right hand side tool bar will allow you to get more detail information of the dataset.
