### ISSUE TITLE
Question about 'global' in Q1

### ISSUE THREAD

**Issue by wangyuhan1234** [neuniversity/ALY6140#26]
Hi all,

Feel confused about how to implement 'global' in question 1. From my knowledge, local variables are enough for the assignment. There seems no need to global any variable. 
Let me know if I misunderstand anything in this question.

Thanks

**Comment by CanlinJiang** [comment]
We have same confusion...

**Comment by mziyadi** [comment]
Don't forget that this information could be misleading. You don't necessarily need global variables. 
As far as you are to get the results by group function, it should be ok.
