### ISSUE TITLE
About extracting data from Github

### ISSUE THREAD

**Issue by siuol456** [neuniversity/ALY6140#30]
Hi all,
Currently, I am struggling with reading a data from github, but it keeps showing that the link is invalid while I can actually see the data from that link. So does that mean if I want to get that data I need the approval of the original owner?

Best,
Yuan-Cheng, Su

**Comment by hansu101** [comment]
Hello,
I suppose the dataset you chose is already expired. Since I can use datasets from github and I did not ask an approval to the owners. 
Thanks.

**Comment by ThatkidfromA** [comment]
Hi,
I have never come to such issues. Have you tried using other data frame? 
Best.
