### ISSUE TITLE
Having trouble with PUSH assignment to online

### ISSUE THREAD

**Issue by Iris0114** [neuniversity/ALY6140#6]
Dear All,

I have followed the professor's instructions in the word document step by step.
When I want to push my assignment to online using the command"git push origin yourfirstname_yourlastname", I am required to type in the username and password of GitHub.
After I typed in, I am still denied and unable to access.
![image](https://user-images.githubusercontent.com/44626622/47956487-57586500-df62-11e8-9c56-e1786dafc468.png)

Does anyone has the same problem with me or know how to fix it?

Thank you a lot!

**Comment by siuol456** [comment]
Hi Iris, 
I think it is solved. You can try it again
