### ISSUE TITLE
How can I use the CAT in MS-OS?

### ISSUE THREAD

**Issue by hansu101** [neuniversity/ALY6140#8]
Hi guys,
In this assignment, I think I would like to use the CAT. But, I found a problem that MS-OS cannot use it.
If someone has an idea for it, please share with me.

**Comment by siuol456** [comment]
I think we could use type for MS.

**Comment by aanranran** [comment]
Hi han,

Unfortunately, CAT is restricted to Mac and Linux system. If you would like to use a similar function to read through your document, try pandas and put all your file under the same folder. It should be work！
