### ISSUE TITLE
Questions for pyABF 

### ISSUE THREAD

**Issue by aanranran** [neuniversity/ALY6140#9]
I try to read the abf document with pyABF package in python. And I found a code in pyABF named 

> abf.setSweep(n) 

For example if `abf.setSweep(3)`, sweeps starting at 0, what does number 3 mean? How should we define the correct number of n?

**Comment by shahtrupt** [comment]
I have similar doubt too. Can someone please explain more details about .abf file and what does channels, sweeps and total length mean?
For given file, we have 
"ABF file (16o03002.abf) with 2 channels, 6 sweeps, and a total length of 0.10 min."
I am confused what does each attribute mean and its significance. Also, please share experiences if anyone has worked with this file format before.
Thanks in advance!
